# Generated by Django 2.2.19 on 2023-02-11 12:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_auto_20230211_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping_card',
            new_name='ShoppingСard',
        ),
    ]
