# Generated by Django 2.2.19 on 2023-02-11 12:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_auto_20230211_1543'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingСard',
            new_name='ShoppingСart',
        ),
    ]
